name: Create release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{secrets.GIT_PUSH_TOKEN}}
      - name: Create release commit
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y git-buildpackage
          export DEBEMAIL="utsavbalar1231@gmail.com"
          export DEBFULLNAME='"UtsavBalar1231"'
          git config user.name "UtsavBalar1231"
          git config user.email "utsavbalar1231@gmail.com"
          make dch
      - name: Test
        run: |
          sudo apt-get build-dep --no-install-recommends -y .
          CC=aarch64-linux-gnu- dpkg-buildpackage -a arm64 -d -b -nc -uc
      - name: Push
        run: |
          git push
